### PR TITLE
Updating Russian localization 1.20.x

### PR DESCRIPTION
**Pull request by Secret-Rabbit**

### CODE REVIEW

**Comment by dtkdtk** [comment]
"поток" is a stream, "флакс" is a flux. Filled by stream instruments? what? It is better not to translate this literally

**Comment by Secret-Rabbit** [comment]
Well, again and again. Do we need to make two alternative translations? What is the problem with translating a word the way it is translated? Is there at least 1 argument for this? It would be okay if there was a word that is absent in Russian, but there it is quite a normal and existing word

**Comment by Secret-Rabbit** [comment]
There are enough words in translation that are missing or very unpopular in the Russian language. Why do we need another word that does not exist in Russian?

**Comment by dtkdtk** [comment]
The translation originally contained the word "флакс" (1.12). Translating this word as "stream/flow" is the creation of an alternative translation that you are talking about.
It’s unpleasant when switching to new versions to see the word "поток" instead of the word "флакс"... Stream of what? Where does the flow go, where does it start?
If you translate absolutely all the words, the translation will sound quite strange, something like "Она - мой углепластик" as in the unofficial translation of GTA SA
I think it is better to leave the word "флакс" in its original sound, because not all words need to be translated (even if the translation seems quite logical and understandable). With the same success, you can translate, for example, the abbreviation "RF" as "ЕПКК" (this example is incorrect, and I know it)

Please don't translate everything literally

**Comment by Secret-Rabbit** [comment]
I have already played enough and read the translations of previous versions that are not similar to each other. Take 4 versions (1.5.2, 1.6.4, 1.7.10, 1.12.2). For some reason, the names are different everywhere, and you don't resent it. I have translated the entire series of mods for versions 1.15.2 and higher, and I will continue to translate in order to prevent what was happening in the old versions

**Comment by KingLemming** [comment]
The intended word is Flux, not Stream.

**Pull request closed without merging**
